apiVersion: v1
kind: Service
metadata:
  name: webapp1
  namespace: default
  labels:
    app: webapp1
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31804
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: webapp1