apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: pabeagle/pablo
        command: ["/bin/sh"]
        args: ["./init.sh"]
        env:
        - name: POC_DATABASE_ENGINE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_ENGINE
        ports:
        - containerPort: 8000